# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='D:\\Aavartan support\\auction\\auctionapp-master\\auctionapp-master\\bidapp\\bidding/media/default/fairy-tail.jpg', upload_to='item/'),
        ),
    ]
