# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionevent',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='D:\\Aavartan support\\auction\\auctionapp-master\\bidapp\\bidding/media/default/fairy-tail.jpg', upload_to='item/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
